apiVersion: v1
kind: Service
metadata:
  name: youtube-downloader-python-service
spec:
  selector:
    app: youtube-downloader
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-downloader
spec:
  selector:
    matchLabels:
      app: youtube-downloader
  replicas: 1
  template:
    metadata:
      labels:
        app: youtube-downloader
    spec:
      containers:
      - name: youtube-downloader
        image: alvinwong12/youtube-downloader:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000